name = "stacks-node"

[builders."docker:generic"]
enabled = true
enable_go_build_cache = true

[builders."docker:go"]
enabled = false

[runners."local:docker"]
enabled = true
keep_containers = false

[runners."cluster:k8s"]
enabled = true

[global.build_config]
enable_go_build_cache = true


[[testcases]]
name = "blocks"
instances = { min = 1, max = 1000 }
 [testcases.params]
  stacks_tip_height = { type = "int", default = 15 }
  sortition_fraction = { type = "int", default = 90 }
  fork_fraction = { type = "int", default = 90 }
  num_blocks = { type = "int", default = 100 }
  verify_chain = { type = "bool", default = true }
